language: bash
services: docker

env:
  global:
    - PROJECT=nomad
    - NAMESPACE=makeomatic
    - PUSH_NAMESPACES=makeomatic

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  # Set container variant name which defines tag name (aka container:version-variant)
  - "[ ${TRAVIS_BRANCH} == master ] || export VARIANT=${TRAVIS_BRANCH}"

script:
  - .travis/build-image $NAMESPACE/$PROJECT .
  - ~/official-images/test/run.sh $(docker images -q | head -n1)

after_success:
  - |
    # List of newly created images
    export images=$(docker images | grep "^$NAMESPACE/$PROJECT" | tr -s '[:space:]' | cut -f1,2 -d' ' | sed 's/ /:/')

    # Check if not PR and namespace (org or user) is in the push list PUSH_NAMESPACES.
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && ( echo "${PUSH_NAMESPACES}" | grep -qw "${TRAVIS_REPO_SLUG%/*}" )
    [ $? -eq 0 ] || exit 0

    # Push to docker when DEPLOY is true
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    for image in $images; do docker push $image; done

after_script:
  - docker images
